### ISSUE TITLE
Change page from Element context

### ISSUE THREAD

**Issue by way2muchnoise** [AfterLifeLochie/fontbox#14]
This is a feature request for use in the clicked method of an Element.
The reason for it is to use an index list and when clicking on Elements it should change the page.
Index Example:
![](http://puu.sh/gxnX5/a731ef5c34.jpg)
Some things that might be nice is having a way to find the a page based on a heading or maybe just a pice of content on the page?

**Comment by AfterLifeLochie** [comment]
Use the `id` field in the heading to set an ID. This is the equivalent of creating an anchor or an item in a table of contents, so make sure the ID you set is unique.

Later on you can jump to this element by ID (some sort of `goToElement(string id)` will exist. You'll also be able to include an automatically-generated table of contents which create clickable links to each of these associated ID locations in the book.

**Comment by AfterLifeLochie** [comment]
Resolved fully in unstable @ 1ba8e78ab47eac76e1c8c098c679dd8d987e9c25
